name: clang-format Check
on: [push, pull_request, workflow_dispatch]
jobs:
  formatting-check:
    name: Formatting Check
    runs-on: ubuntu-latest
    strategy:
      matrix:
        path:
          - check: "lib/compiler"
          - check: "lib/ffi"
          - check: "lib/fmt"
          - check: "lib/kernels"
          - check: "lib/op-attrs"
          - check: "lib/pcg"
          - check: "lib/runtime/ffi"
          - check: "lib/runtime/include"
          - check: "lib/runtime/src"
          - check: "lib/runtime/test"
          - check: "lib/substitutions"
          - check: "lib/triton"
          - check: "lib/utils"
          - check: "python"
          - check: "scripts"
          - check: "tests"
          - check: "examples"
          - check: "bindings"
          - check: "config"
          - check: "deps"
          - check: "packaging"
          - check: "substitutions"
    steps:
      - uses: actions/checkout@v2
      - name: Run clang-format style check for C/C++/Protobuf programs.
        uses: jidicula/clang-format-action@v4.8.0
        with:
          clang-format-version: "15"
          check-path: ${{ matrix.path['check'] }}
          exclude-regex: ${{ matrix.path['exclude'] }}
