name: Format Script

on: [push]

jobs:
  format:
    name: Format Script
    runs-on: ubuntu-latest

    steps:
    - name: Check out code
      uses: actions/checkout@v2

    - name: Execute format.sh script
      run: scripts/format.sh

